/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */
/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef ssize_t */

/* Define if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define if you have the `fcntl' function. */
#define HAVE_FCNTL 1

/* Define if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define if you have the `fsync' function. */
#define HAVE_FSYNC 1

/* Define if you have the `ftruncate' function. */
#define HAVE_FTRUNCATE 1

/* Define if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define if you have the `gmtime_r' function. */
#define HAVE_GMTIME_R 1

/* Define if you have the `htonl' function. */
#define HAVE_HTONL 1

/* Define if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have the `pcre' library (-lpcre). */
/* #undef HAVE_LIBPCRE */

/* Define if you have the `pcreposix' library (-lpcreposix). */
/* #undef HAVE_LIBPCREPOSIX */

/* Define if you have the `regex' library (-lregex). */
/* #undef HAVE_LIBREGEX */

/* Define if you have the `rx' library (-lrx). */
/* #undef HAVE_LIBRX */

/* Define if you have the `localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define if you have the `lockf' function. */
#define HAVE_LOCKF 1

/* Define if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the `mktime' function. */
#define HAVE_MKTIME 1

/* Define if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* same as HAVE_REGEX_LIB, for backward compatibility. */
#define HAVE_REGCOMP 1

/* Define if you have the <regex.h> header file. */
#define HAVE_REGEX_H 1

/* Define if you have POSIX-compatible regexp library (regex, GNU rx or PCRE).
   */
#define HAVE_REGEX_LIB 1

/* Define if you have the `sleep' function. */
#define HAVE_SLEEP 1

/* Define if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define if you have the <sysexits.h> header file. */
#define HAVE_SYSEXITS_H 1

/* Define if you have the <sys/locking.h> header file. */
/* #undef HAVE_SYS_LOCKING_H */

/* Define if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define if you have the `_chsize' function. */
/* #undef HAVE__CHSIZE */

/* Define if you have the `_locking' function. */
/* #undef HAVE__LOCKING */

/* Define if you have the `_sleep' function. */
/* #undef HAVE__SLEEP */

/* Define if you have the `_snprintf' function. */
/* #undef HAVE__SNPRINTF */

/* Define if you have the `_vsnprintf' function. */
/* #undef HAVE__VSNPRINTF */

/* Name of package */
#define PACKAGE "libstrfunc"

/* Define if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Version number of package */
#define VERSION "7"

/* Define if your processor stores words with the most significant byte first
   (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef ssize_t */
/* Define if you have the <regex.h> header file.  */
#define HAVE_REGEX_H 1

/* Define if you have the GNU rx library. */
/* #undef HAVE_RXPOSIX_H */

/* Define if you have the PCRE library */
#define HAVE_PCREPOSIX_H 1

/* Define if you have tzname() */
/* #undef HAVE_TZNAME */

/* Define if you have struct tm_zone */
#define HAVE_TM_ZONE 1
