# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# real mans

SHELL = /bin/bash

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/libstrfunc
pkglibdir = $(libdir)/libstrfunc
pkgincludedir = $(includedir)/libstrfunc
top_builddir = ..

ACLOCAL = ${SHELL} /home/fang/git/fang/libstrfunc-7.4.6/missing --run aclocal
AUTOCONF = @echo autoconf not available
AUTOMAKE = ${SHELL} /home/fang/git/fang/libstrfunc-7.4.6/missing --run automake
AUTOHEADER = @echo autoheader not available

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = 
build_triplet = x86_64-unknown-linux-gnu
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
target_alias = 
target_triplet = x86_64-unknown-linux-gnu
AMTAR = ${SHELL} /home/fang/git/fang/libstrfunc-7.4.6/missing --run tar
AR = /usr/bin/ar
AS = @AS@
AWK = mawk
CC = gcc
CONFIGURE_DEPENDS = configure.in aclocal.m4
CPP = gcc -E
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
ECHO = echo
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = libstrfunc
PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/ucb:/usr/ccs/bin
RANLIB = ranlib
STRIP = strip
VERSION = 7
YACC = yacc
am__include = include
am__quote = 
install_sh = /home/fang/git/fang/libstrfunc-7.4.6/install-sh

real_mans = sf_cfg.3 sf_cgi.3 sf_file.3 sf_fmt.3 sf_mem.3 sf_mime.3 \
	sf_misc.3 sf_sbuf.3 sf_sed.3 sf_split.3 sf_svect.3 sf_time.3 strfunc.3


# aliases of strfunc.3
strfunc_mans = libstrfunc.3

# aliases of sf_svect.3
sf_svect_mans = slist.3 sinit.3 svect.3 sadd.3 sadd2.3 sadd_attach.3 sdel.3 \
	sins.3 simport.3 sfree.3 sclear.3 sarray.3 mkarray.3 charize.3 \
	sfind.3 scfind.3 find.3 cfind.3 count_values.3 copy_values.3 \
	free_values.3 sget.3 scget.3 scgetp.3 scopy.3


# aliases of sf_split.3
sf_split_mans = split.3 splitf.3 splitquotable.3 split_network.3 sjoin.3 join.3

# aliases of sf_cgi.3
sf_cgi_mans = param.3 param2.3 params.3 set_cookie.3 cookie.3 cookies.3 \
	html_quote.3 url_encode.3 url_decode.3 getlanguageprefs.3


# aliases of sf_mime.3
sf_mime_mans = base64_encode.3 base64_decode.3 quoted_printable_decode.3 \
	mime_word_decode.3


# aliases of sf_time.3
sf_time_mans = strtotime.3 timetostr.3

# aliases of sf_cfg.3
sf_cfg_mans = cfgread.3 cfgget.3 cfgget2.3

# aliases of sf_fmt.3
sf_fmt_mans = format_init.3 format_free.3 format_metarule.3 formatf.3 \
	format_lastsize.3 format_lastresult.3 format_detach.3


# aliases of sf_sbuf.3
sf_sbuf_mans = sbuf.3 sbuf_init.3 sbuf_free.3 sbuf_detach.3 sbuf_clear.3 \
	sbuf_zero.3 sbuf_extend.3 sbuf_add.3 sbuf_add2.3 sbuf_sprintf.3 \
	sbuf_fetch.3 sbuf_fgets.3


# aliases of sf_sed.3
sf_sed_mans = sed.3 sed_compile.3 sed_exec.3 sed_free.3

# aliases of sf_file.3
sf_file_mans = initfdpos.3 initFILEpos.3 adjfdpos.3 adjFILEpos.3

# aliases of sf_misc.3
sf_misc_mans = eq.3 ecq.3 countchar.3 countchar2.3 countstr.3 replace.3 \
	replace_detach.3 limittextwidth.3


# aliases of sf_mem.3
sf_mem_mans = strndup.3 sf_strdup.3 sf_malloc.3 sf_calloc.3 sf_realloc.3 \
	strfunc_ctl.3


# all of the aliases
aliased_mans = $(strfunc_mans) $(sf_svect_mans) $(sf_split_mans) \
	$(sf_cgi_mans) $(sf_mime_mans) $(sf_time_mans) $(sf_cfg_mans) \
	$(sf_fmt_mans) $(sf_sbuf_mans) $(sf_sed_mans) $(sf_file_mans) \
	$(sf_misc_mans) $(sf_mem_mans)


man_MANS = $(real_mans) $(aliased_mans)

CLEANFILES = $(aliased_mans)

EXTRA_DIST = $(man_MANS)
extra_cvsignore = Makefile
subdir = man
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h $(top_builddir)/strfunc.h \
	$(top_builddir)/getopt.h
CONFIG_CLEAN_FILES =
DIST_SOURCES =

NROFF = nroff
MANS = $(man_MANS)
DIST_COMMON = Makefile.am Makefile.in
all: all-am

.SUFFIXES:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in: # Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  man/Makefile
Makefile: # $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
uninstall-info-am:

man3dir = $(mandir)/man3
install-man3: $(man3_MANS) $(man_MANS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(man3dir)
	@list='$(man3_MANS) $(dist_man3_MANS) $(nodist_man3_MANS)'; \
	l2='$(man_MANS) $(dist_man_MANS) $(nodist_man_MANS)'; \
	for i in $$l2; do \
	  case "$$i" in \
	    *.3*) list="$$list $$i" ;; \
	  esac; \
	done; \
	for i in $$list; do \
	  if test -f $(srcdir)/$$i; then file=$(srcdir)/$$i; \
	  else file=$$i; fi; \
	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
	  echo " $(INSTALL_DATA) $$file $(DESTDIR)$(man3dir)/$$inst"; \
	  $(INSTALL_DATA) $$file $(DESTDIR)$(man3dir)/$$inst; \
	done
uninstall-man3:
	@$(NORMAL_UNINSTALL)
	@list='$(man3_MANS) $(dist_man3_MANS) $(nodist_man3_MANS)'; \
	l2='$(man_MANS) $(dist_man_MANS) $(nodist_man_MANS)'; \
	for i in $$l2; do \
	  case "$$i" in \
	    *.3*) list="$$list $$i" ;; \
	  esac; \
	done; \
	for i in $$list; do \
	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
	  echo " rm -f $(DESTDIR)$(man3dir)/$$inst"; \
	  rm -f $(DESTDIR)$(man3dir)/$$inst; \
	done
tags: TAGS
TAGS:


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(MANS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(man3dir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-generic distclean-libtool

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-man

install-exec-am:

install-info: install-info-am

install-man: install-man3

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

uninstall-am: uninstall-info-am uninstall-man

uninstall-man: uninstall-man3

.PHONY: all all-am check check-am clean clean-generic clean-libtool \
	distclean distclean-generic distclean-libtool distdir dvi \
	dvi-am info info-am install install-am install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-man3 install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic \
	mostlyclean-libtool uninstall uninstall-am uninstall-info-am \
	uninstall-man uninstall-man3


# if anyone knows a way to compress these all 
# to a single rule -- let the author know
$(strfunc_mans): strfunc.3
	cp strfunc.3 $@

$(sf_svect_mans): sf_svect.3
	cp sf_svect.3 $@

$(sf_split_mans): sf_split.3
	cp sf_split.3 $@

$(sf_cgi_mans): sf_cgi.3
	cp sf_cgi.3 $@

$(sf_mime_mans): sf_mime.3
	cp sf_mime.3 $@

$(sf_time_mans): sf_time.3
	cp sf_time.3 $@

$(sf_cfg_mans): sf_cfg.3
	cp sf_cfg.3 $@

$(sf_fmt_mans): sf_fmt.3
	cp sf_fmt.3 $@

$(sf_sbuf_mans): sf_sbuf.3
	cp sf_sbuf.3 $@

$(sf_sed_mans): sf_sed.3
	cp sf_sed.3 $@

$(sf_file_mans): sf_file.3
	cp sf_file.3 $@

$(sf_misc_mans): sf_misc.3
	cp sf_misc.3 $@

$(sf_mem_mans): sf_mem.3
	cp sf_mem.3 $@

# aliased mans should be ignored by CVS
all: .cvsignore
.cvsignore: Makefile.am
	echo $(extra_cvsignore) $(aliased_mans) | tr ' ' '\n'  > $@
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
