# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/bash

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/libstrfunc
pkglibdir = $(libdir)/libstrfunc
pkgincludedir = $(includedir)/libstrfunc
top_builddir = ..

ACLOCAL = ${SHELL} /home/fang/git/fang/libstrfunc-7.4.6/missing --run aclocal
AUTOCONF = @echo autoconf not available
AUTOMAKE = ${SHELL} /home/fang/git/fang/libstrfunc-7.4.6/missing --run automake
AUTOHEADER = @echo autoheader not available

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = 
build_triplet = x86_64-unknown-linux-gnu
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
target_alias = 
target_triplet = x86_64-unknown-linux-gnu
AMTAR = ${SHELL} /home/fang/git/fang/libstrfunc-7.4.6/missing --run tar
AR = /usr/bin/ar
AS = @AS@
AWK = mawk
CC = gcc
CONFIGURE_DEPENDS = configure.in aclocal.m4
CPP = gcc -E
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
ECHO = echo
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = libstrfunc
PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/ucb:/usr/ccs/bin
RANLIB = ranlib
STRIP = strip
VERSION = 7
YACC = yacc
am__include = include
am__quote = 
install_sh = /home/fang/git/fang/libstrfunc-7.4.6/install-sh

noinst_PROGRAMS = sed fmt split time replace mime sbuf cfg param

TESTS = sed time fmt param

LDADD = $(top_builddir)/libstrfunc.la
subdir = test
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h $(top_builddir)/strfunc.h \
	$(top_builddir)/getopt.h
CONFIG_CLEAN_FILES =
noinst_PROGRAMS = sed$(EXEEXT) fmt$(EXEEXT) split$(EXEEXT) time$(EXEEXT) \
	replace$(EXEEXT) mime$(EXEEXT) sbuf$(EXEEXT) cfg$(EXEEXT) \
	param$(EXEEXT)
PROGRAMS = $(noinst_PROGRAMS)

cfg_SOURCES = cfg.c
cfg_OBJECTS = cfg.$(OBJEXT)
cfg_LDADD = $(LDADD)
cfg_DEPENDENCIES = $(top_builddir)/libstrfunc.la
cfg_LDFLAGS =
fmt_SOURCES = fmt.c
fmt_OBJECTS = fmt.$(OBJEXT)
fmt_LDADD = $(LDADD)
fmt_DEPENDENCIES = $(top_builddir)/libstrfunc.la
fmt_LDFLAGS =
mime_SOURCES = mime.c
mime_OBJECTS = mime.$(OBJEXT)
mime_LDADD = $(LDADD)
mime_DEPENDENCIES = $(top_builddir)/libstrfunc.la
mime_LDFLAGS =
param_SOURCES = param.c
param_OBJECTS = param.$(OBJEXT)
param_LDADD = $(LDADD)
param_DEPENDENCIES = $(top_builddir)/libstrfunc.la
param_LDFLAGS =
replace_SOURCES = replace.c
replace_OBJECTS = replace.$(OBJEXT)
replace_LDADD = $(LDADD)
replace_DEPENDENCIES = $(top_builddir)/libstrfunc.la
replace_LDFLAGS =
sbuf_SOURCES = sbuf.c
sbuf_OBJECTS = sbuf.$(OBJEXT)
sbuf_LDADD = $(LDADD)
sbuf_DEPENDENCIES = $(top_builddir)/libstrfunc.la
sbuf_LDFLAGS =
sed_SOURCES = sed.c
sed_OBJECTS = sed.$(OBJEXT)
sed_LDADD = $(LDADD)
sed_DEPENDENCIES = $(top_builddir)/libstrfunc.la
sed_LDFLAGS =
split_SOURCES = split.c
split_OBJECTS = split.$(OBJEXT)
split_LDADD = $(LDADD)
split_DEPENDENCIES = $(top_builddir)/libstrfunc.la
split_LDFLAGS =
time_SOURCES = time.c
time_OBJECTS = time.$(OBJEXT)
time_LDADD = $(LDADD)
time_DEPENDENCIES = $(top_builddir)/libstrfunc.la
time_LDFLAGS =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir) -I$(top_builddir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/cfg.Po $(DEPDIR)/fmt.Po \
	$(DEPDIR)/mime.Po $(DEPDIR)/param.Po \
	$(DEPDIR)/replace.Po $(DEPDIR)/sbuf.Po \
	$(DEPDIR)/sed.Po $(DEPDIR)/split.Po \
	$(DEPDIR)/time.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2
DIST_SOURCES = cfg.c fmt.c mime.c param.c replace.c sbuf.c sed.c split.c \
	time.c
DIST_COMMON = README Makefile.am Makefile.in
SOURCES = cfg.c fmt.c mime.c param.c replace.c sbuf.c sed.c split.c time.c

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in: # Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  test/Makefile
Makefile: # $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
cfg$(EXEEXT): $(cfg_OBJECTS) $(cfg_DEPENDENCIES) 
	@rm -f cfg$(EXEEXT)
	$(LINK) $(cfg_LDFLAGS) $(cfg_OBJECTS) $(cfg_LDADD) $(LIBS)
fmt$(EXEEXT): $(fmt_OBJECTS) $(fmt_DEPENDENCIES) 
	@rm -f fmt$(EXEEXT)
	$(LINK) $(fmt_LDFLAGS) $(fmt_OBJECTS) $(fmt_LDADD) $(LIBS)
mime$(EXEEXT): $(mime_OBJECTS) $(mime_DEPENDENCIES) 
	@rm -f mime$(EXEEXT)
	$(LINK) $(mime_LDFLAGS) $(mime_OBJECTS) $(mime_LDADD) $(LIBS)
param$(EXEEXT): $(param_OBJECTS) $(param_DEPENDENCIES) 
	@rm -f param$(EXEEXT)
	$(LINK) $(param_LDFLAGS) $(param_OBJECTS) $(param_LDADD) $(LIBS)
replace$(EXEEXT): $(replace_OBJECTS) $(replace_DEPENDENCIES) 
	@rm -f replace$(EXEEXT)
	$(LINK) $(replace_LDFLAGS) $(replace_OBJECTS) $(replace_LDADD) $(LIBS)
sbuf$(EXEEXT): $(sbuf_OBJECTS) $(sbuf_DEPENDENCIES) 
	@rm -f sbuf$(EXEEXT)
	$(LINK) $(sbuf_LDFLAGS) $(sbuf_OBJECTS) $(sbuf_LDADD) $(LIBS)
sed$(EXEEXT): $(sed_OBJECTS) $(sed_DEPENDENCIES) 
	@rm -f sed$(EXEEXT)
	$(LINK) $(sed_LDFLAGS) $(sed_OBJECTS) $(sed_LDADD) $(LIBS)
split$(EXEEXT): $(split_OBJECTS) $(split_DEPENDENCIES) 
	@rm -f split$(EXEEXT)
	$(LINK) $(split_LDFLAGS) $(split_OBJECTS) $(split_LDADD) $(LIBS)
time$(EXEEXT): $(time_OBJECTS) $(time_DEPENDENCIES) 
	@rm -f time$(EXEEXT)
	$(LINK) $(time_LDFLAGS) $(time_OBJECTS) $(time_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/cfg.Po
include $(DEPDIR)/fmt.Po
include $(DEPDIR)/mime.Po
include $(DEPDIR)/param.Po
include $(DEPDIR)/replace.Po
include $(DEPDIR)/sbuf.Po
include $(DEPDIR)/sed.Po
include $(DEPDIR)/split.Po
include $(DEPDIR)/time.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CCDEPMODE) $(depcomp) \
	$(LTCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CCDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; \
	srcdir=$(srcdir); export srcdir; \
	list='$(TESTS)'; \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
	        xpass=`expr $$xpass + 1`; \
	        failed=`expr $$failed + 1`; \
	        echo "XPASS: $$tst"; \
	      ;; \
	      *) \
	        echo "PASS: $$tst"; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
	        xfail=`expr $$xfail + 1`; \
	        echo "XFAIL: $$tst"; \
	      ;; \
	      *) \
	        failed=`expr $$failed + 1`; \
	        echo "FAIL: $$tst"; \
	      ;; \
	      esac; \
	    fi; \
	  done; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="All $$all tests passed"; \
	    else \
	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all tests failed"; \
	    else \
	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
	    fi; \
	  fi; \
	  dashes=`echo "$$banner" | sed s/./=/g`; \
	  echo "$$dashes"; \
	  echo "$$banner"; \
	  echo "$$dashes"; \
	  test "$$failed" -eq 0; \
	fi

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-TESTS check-am clean clean-generic \
	clean-libtool clean-noinstPROGRAMS distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	tags uninstall uninstall-am uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
